- name: Hello World Sample
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Setting JSON data
      set_fact:
        jsondata: "{{ user_data | from_json }}"
        
    - name: Getting JSON data for printing
      debug:
        msg: "Hello World!: {{survey_var}} {{jsondata.user_email}}"
