- name: Hello World Sample
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Hello Message
      set_fact:
        jsondata: "{{ user_data | from_json }}"
      debug:
        msg: "Hello World!: {{survey_var}} {{jsondata.user_email}}"
