- name: Hello World Sample
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Setting JSON data
      set_fact:
        jsondata: "{{ user_data | from_json }}"
        
    - name: Getting JSON data for printing
      debug:
        msg: "Hello World!: {{survey_var}} {{jsondata.user_email}}"
        
    - name: Wait 300 seconds for port 8000 to become open on the host, don't start checking for 10 seconds
      wait_for:
        port: 8000
        delay: 40
        
    - name: Printing
      debug:
        msg: "2nd print statement"
